export interface BasePatagonia {
  'ani': string;
  'id grabacion': string;
  'agente': string;
  'extension': string;
  'fecha grabacion': string;
  'hora grabacion': string;
  'duracion grabacion': string;
  'servicio': string;
  'url': string;
  'servidor': string;
  'tipo de resultado': string;
  'resultado': string;
  'transcripcion': string;
  'duracion transcripcion (minutos)': string;
  'fecha/hora creacion primer texto': string;
  'usuario creacion primer texto': string;
  'fecha/hora primer texto usuario resultado': string;
  'fecha/hora creacion ultimo texto': string;
  'fecha creacion resultado': string;
  'usuario creacion resultado':string;
  'user': string;
  'site': string;
  'asesor': string;
  'dni': string;
  'login': string;
  'fechau': string;
  'duracion grabacion redondeada (en minutos)': string;
  'objetivo tmo (en minutos)': string;
  'desvio tmo * 3 (en minutos)': string;
  'desvio tmo * 4 (en minutos)': string;
  'selecciono tmo': string;
  'supervisor': string;
  'horas gap': string;
  'hora guardado de ficha': string;
  'tiempo de transcripcion en hs': string;
  'controlar': string;
  'tiempo de llamada': string;
  '1er control': string;
  '2do control': string;
  '3er control': string;
  '4to control': string;
  'cuento trans. correctas': string;
  'cuento trans. incorrectas': string;
  'tiempo en minutos': string;
  'objellamada': string;
  'mes': string;
  'semana': string;
}
